name: dartling_types
author: Dzenan Ridjanovic
homepage: http://ondart.me/
version: 2.0.1
description: a generic web component done by meta-programming in dartling.
environment:
  sdk: '>=1.9.3 <2.0.0'
dependencies:
  browser: any
  dartling: any
  dartling_default_app: any
  