name: dartling_types
author: Dzenan Ridjanovic
homepage: http://ondart.me/
version: 0.0.2
description: dartling_types application that uses dartling for its model.
environment:
  sdk: '>=1.9.3 <2.0.0'
dependencies:
  browser: any
  dartling:
    git: 'https://github.com/dzenanr/dartling.git'
  dartling_default_app:
    git: 'https://github.com/dzenanr/dartling_default_app.git'
  